name: task_manager
description: "Task Manger Project ..."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
# ++++++++++++++++++++
  get: ^4.7.2
  pin_code_fields: ^8.0.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.3.1
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
#    ////////////////////////
  flutter_gen: ^5.11.0
  build_runner:
  flutter_gen_runner:


  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/


  uses-material-design: true

